### ISSUE TITLE
Advanced Costum Card not shown

### ISSUE THREAD

**Issue by DaHype** [DustyArmstrong/homeassistant-desktop#13]
### What's on your mind?

Hi,

Since some days, i use the costum advanced camera card  on Dashboard ( before name was Frigate Card) for my cams.
On Browser and also Smartphone App all OK. But if i use the Home Assistant Desktop from you, the cards don't display.
Get this error:

![Image](https://github.com/user-attachments/assets/3d01b3fd-a97e-41b5-a4b5-0931948bfca2)

Is it possible to fix this?
If i use Web RTC card or any other camera card, it works. Only with Frigate i have this issue.

Thank you

**Comment by DustyArmstrong** [comment]
Hello, I use the Advanced Camera Card too which works OK - so Advanced Camera Card works for you on browser and in the Android/iOS app but not in this desktop app?

Can you share your card config? May be something that isn't rendering but normally it just wouldn't display anything at all, that error message indicates a configuration problem with the element config. The discrepancy may [be due to caching](https://www.reddit.com/r/homeassistant/comments/zj6gqf/custom_element_doesnt_exist_on_all_but_one/) - can you try clearing your cache on the browser and see if the card now fails with the same error?

**Comment by DustyArmstrong** [comment]
OK mine still says frigate-card, can you try renaming it back in your card config: 

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.whatever
    live_provider: go2rtc
live:
  preload: true
menu:
  buttons:
    cameras:
      enabled: false
```
